# Generated by Django 2.1.1 on 2018-12-13 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_evaluacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='Evidencia_estudiante',
            field=models.FileField(blank=True, null=True, upload_to='evidencias/'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='Evidencia_grupoColegiados',
            field=models.FileField(blank=True, null=True, upload_to='evidencias/'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='Evidencia_instancias',
            field=models.FileField(blank=True, null=True, upload_to='evidencias/'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='Resultados_periodos',
            field=models.FileField(blank=True, null=True, upload_to='evidencias/'),
        ),
    ]
