# Generated by Django 2.1.2 on 2018-11-28 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_docentes', '0003_auto_20181126_0003'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Docente',
        ),
    ]
