# Generated by Django 2.1.1 on 2018-11-29 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='promocion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hay_proceso_promocion', models.BooleanField(default=False)),
                ('Hay_reglamento_proceso', models.BooleanField(default=False)),
                ('Descripcion', models.TextField(blank=True, default='', null=True)),
                ('Hay_difusion_proceso', models.BooleanField(default=False)),
                ('DescripcionDifusion', models.TextField(blank=True, default='', null=True)),
            ],
        ),
    ]
