# Generated by Django 2.1.1 on 2018-12-07 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_promocion', '0002_promocion_evidencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Evidencia', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='promocion',
            name='Evidencia',
        ),
    ]
