# Generated by Django 2.1.1 on 2018-12-07 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_promocion', '0003_auto_20181207_1341'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Evidencia',
        ),
        migrations.AddField(
            model_name='promocion',
            name='Evidencia',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
