# Generated by Django 2.1.1 on 2018-12-13 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_promocion', '0004_auto_20181207_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocion',
            name='Evidencia',
            field=models.FileField(blank=True, null=True, upload_to='evidencias/'),
        ),
    ]
